In [4]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [5]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt , yp in zip (y_true, y_predicted):
        total_error += abs(yt - yp)
    print('Total error:', total_error)

    mae = total_error / len(y_true)
    print('MAE:', mae)
    return mae

In [6]:
mae(y_true, y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [7]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [8]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [9]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [10]:
np.log([0.0000000000001])

array([-29.93360621])

In [12]:
eplison = 1e-15

In [19]:
y_predicted_new = [max(i, eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [20]:
y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [21]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [22]:
-np.mean(y_true * np.log(y_predicted_new) + (1- y_true)* np.log(1- y_predicted_new))

17.2696280766844

In [23]:
def log_loss(y_true, y_predicted):
    eplison = 1e-15
    y_predicted_new = [max(i, eplison) for i in y_predicted]
    y_predicted_new = [min(i, 1- eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1- y_true) * np.log(1-y_predicted_new))


In [24]:
log_loss(y_true, y_predicted)

17.2696280766844

# with using numpy

In [25]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1,0,0.5])

In [26]:
def mse(y_true,y_predicted):
    total_error = 0
    for yt , yp in zip (y_true, y_predicted):
        total_error += (yt - yp)** 2
    print('Total squered error:', total_error)

    mse = total_error / len(y_true)
    print('Mean Squared Error:', mse)
    return mse

In [27]:
mse(y_true, y_predicted)

Total squered error: 1.83
Mean Squared Error: 0.366


0.366

In [28]:
# by using numpy 
np.mean(np.square(y_true - y_predicted))

0.366