In [1]:
import numpy as np

In [2]:
revenue= np.array([[150, 280, 220], [25, 36, 42],[15, 20, 24]])
expenses = np.array([[60, 80, 100], [12, 17, 25], [6, 12, 15]])

In [3]:
profit = revenue - expenses
profit

array([[ 90, 200, 120],
       [ 13,  19,  17],
       [  9,   8,   9]])

In [5]:
price_per_unit = np.array([1200, 600, 1400])
units = np.array([[35, 45, 55], [10,15,20],[5, 7, 9]])

In [7]:
np.dot(price_per_unit ,units)

array([55000, 72800, 90600])

# Exercise

In [8]:
revenue_usd = np.array([[200, 220, 250],[68,79,105],[110,140,180],[80,85,90]])
revenue_inr = 75*revenue_usd
revenue_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [9]:
units_sold = np.array([[50, 60, 25],[10,13,5], [40,70, 52]])
price_per_unit = np.array([20,30, 15])

In [11]:
total_sales_per_unit = np.dot(price_per_unit, units_sold)
total_sales_per_unit

array([1900, 2640, 1430])